export type Risk = "Critical" | "High" | "Medium" | "Balanced" | "Oversupply";

export const forecastData = [
  { month: "Jan 24", demand: 5.2, supply: 4.7 },
  { month: "Apr 24", demand: 5.5, supply: 4.9 },
  { month: "Jul 24", demand: 5.8, supply: 5.1 },
  { month: "Oct 24", demand: 6.1, supply: 5.3 },
  { month: "Jan 25", demand: 6.5, supply: 5.6 },
  { month: "Apr 25", demand: 6.9, supply: 5.8 },
  { month: "Jul 25", demand: 7.4, supply: 6.1 },
  { month: "Oct 25", demand: 7.7, supply: 6.4 },
  { month: "Jan 26", demand: 8.0, supply: 6.6 },
  { month: "Apr 26", demand: 8.4, supply: 6.9 },
  { month: "Jul 26", demand: 8.8, supply: 7.1 },
  { month: "Oct 26", demand: 9.2, supply: 7.4 },
  { month: "Jan 27", demand: 9.6, supply: 7.7 },
  { month: "Apr 27", demand: 10.0, supply: 8.0 },
  { month: "Jul 27", demand: 10.4, supply: 8.3 },
];

export const gapRows = [
  {
    rank: 1,
    skill: "AI / ML Engineer",
    sector: "IT & ITES",
    state: "Rajasthan",
    demand: 42500,
    supply: 27100,
    gap: 15400,
    risk: "Critical" as Risk,
    growth: "+31%",
  },
  {
    rank: 2,
    skill: "Solar PV Technician",
    sector: "Renewable Energy",
    state: "Rajasthan",
    demand: 31800,
    supply: 20600,
    gap: 11200,
    risk: "High" as Risk,
    growth: "+24%",
  },
  {
    rank: 3,
    skill: "Cloud Technician",
    sector: "IT & ITES",
    state: "Karnataka",
    demand: 38900,
    supply: 29200,
    gap: 9700,
    risk: "High" as Risk,
    growth: "+19%",
  },
  {
    rank: 4,
    skill: "EV Technician",
    sector: "Automotive",
    state: "Maharashtra",
    demand: 26400,
    supply: 21100,
    gap: 5300,
    risk: "Medium" as Risk,
    growth: "+14%",
  },
  {
    rank: 5,
    skill: "Data Entry Operator",
    sector: "Business Services",
    state: "Rajasthan",
    demand: 18300,
    supply: 27000,
    gap: -8700,
    risk: "Oversupply" as Risk,
    growth: "-12%",
  },
];

export const skills = [
  { name: "Generative AI", demand: "84.2K", growth: "+42%", confidence: "92%" },
  {
    name: "Cloud Computing",
    demand: "72.8K",
    growth: "+28%",
    confidence: "89%",
  },
  { name: "Cybersecurity", demand: "54.1K", growth: "+24%", confidence: "91%" },
  { name: "Solar PV", demand: "48.7K", growth: "+21%", confidence: "87%" },
  {
    name: "EV Maintenance",
    demand: "43.2K",
    growth: "+18%",
    confidence: "86%",
  },
];

export const sectorData = [
  {
    name: "IT & ITES",
    demand: 2.8,
    growth: "+18.4%",
    gap: "420K",
    color: "#8b72b8",
  },
  {
    name: "Healthcare",
    demand: 1.6,
    growth: "+14.2%",
    gap: "210K",
    color: "#668fcf",
  },
  {
    name: "Renewable Energy",
    demand: 1.1,
    growth: "+26.8%",
    gap: "180K",
    color: "#39a96b",
  },
  {
    name: "Automotive",
    demand: 0.92,
    growth: "+11.7%",
    gap: "96K",
    color: "#e889a8",
  },
  {
    name: "Logistics",
    demand: 0.74,
    growth: "+9.6%",
    gap: "54K",
    color: "#f2a541",
  },
];

export const districts = [
  {
    name: "Jaipur",
    state: "Rajasthan",
    demand: "42,500",
    supply: "27,100",
    gap: "+15,400",
    risk: "Critical" as Risk,
    x: 42,
    y: 40,
  },
  {
    name: "Bengaluru Urban",
    state: "Karnataka",
    demand: "38,900",
    supply: "29,200",
    gap: "+9,700",
    risk: "High" as Risk,
    x: 46,
    y: 72,
  },
  {
    name: "Pune",
    state: "Maharashtra",
    demand: "31,600",
    supply: "27,800",
    gap: "+3,800",
    risk: "Medium" as Risk,
    x: 38,
    y: 65,
  },
  {
    name: "Kota",
    state: "Rajasthan",
    demand: "21,400",
    supply: "19,700",
    gap: "+1,700",
    risk: "Medium" as Risk,
    x: 48,
    y: 45,
  },
  {
    name: "Ajmer",
    state: "Rajasthan",
    demand: "18,200",
    supply: "21,000",
    gap: "-2,800",
    risk: "Oversupply" as Risk,
    x: 36,
    y: 46,
  },
  {
    name: "Chennai",
    state: "Tamil Nadu",
    demand: "27,800",
    supply: "25,300",
    gap: "+2,500",
    risk: "Medium" as Risk,
    x: 57,
    y: 83,
  },
];
